import type { Product } from "@/types";

const tshirtColors = [
  { name: "Weiß", hex: "#FFFFFF" },
  { name: "Schwarz", hex: "#111111" },
  { name: "Marine", hex: "#1E3A5F" },
  { name: "Grau", hex: "#B7BCC4" },
  { name: "Rot", hex: "#C03434" },
];

const sizesApparel = ["XS", "S", "M", "L", "XL", "XXL"];

export const PRODUCTS: Product[] = [
  {
    id: "p_tshirt_classic",
    slug: "premium-t-shirt",
    title: "Premium T-Shirt — Bio Baumwolle",
    category: "textilien",
    subcategory: "t-shirts",
    type: "tshirt",
    priceFrom: 14.9,
    basePrice: 14.9,
    rating: 4.8,
    reviews: 2143,
    description:
      "Hochwertiges T-Shirt aus 100% Bio-Baumwolle, 180 g/m². Perfekt für individuellen Druck — von Einzelstück bis Großauflage.",
    highlights: [
      "100% Bio-Baumwolle, 180 g/m²",
      "Premium Druckqualität (DTG / Siebdruck)",
      "OEKO-TEX® zertifiziert",
      "Vor-/Rückendruck möglich",
    ],
    colors: tshirtColors,
    sizes: sizesApparel,
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 33, topPct: 24, widthPct: 34, heightPct: 50 },
        widthMm: 305,
        heightMm: 406,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "back",
        key: "back" as const,
        label: "Rückseite",
        labelEn: "Back",
        mockup: "/mockups/tshirt/back.png",
        mockupWidth: 840,
        mockupHeight: 848,
        printArea: { leftPct: 32, topPct: 18, widthPct: 36, heightPct: 56 },
        widthMm: 305,
        heightMm: 406,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "chest_left",
        key: "chest_left" as const,
        label: "Brust links",
        labelEn: "Left chest",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 54, topPct: 26, widthPct: 13, heightPct: 14 },
        widthMm: 100,
        heightMm: 100,
        recommendedDpi: 300,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 2.6,
      },
      {
        id: "sleeve_left",
        key: "sleeve_left" as const,
        label: "Ärmel links",
        labelEn: "Left sleeve",
        mockup: "/mockups/tshirt/side.png",
        mockupWidth: 1311,
        mockupHeight: 1200,
        printArea: { leftPct: 18, topPct: 22, widthPct: 22, heightPct: 26 },
        widthMm: 90,
        heightMm: 60,
        recommendedDpi: 300,
        safePct: 6,
        bleedPct: 0,
        additionalPrice: 2.9,
      },
      {
        id: "sleeve_right",
        key: "sleeve_right" as const,
        label: "Ärmel rechts",
        labelEn: "Right sleeve",
        mockup: "/mockups/tshirt/side.png",
        mockupWidth: 1311,
        mockupHeight: 1200,
        printArea: { leftPct: 18, topPct: 22, widthPct: 22, heightPct: 26 },
        widthMm: 90,
        heightMm: 60,
        recommendedDpi: 300,
        safePct: 6,
        bleedPct: 0,
        additionalPrice: 2.9,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 301, y: 200, width: 310, height: 417 },
      },
      {
        id: "back",
        label: "Rückseite",
        image: "/mockups/tshirt/back.png",
        area: { x: 269, y: 153, width: 302, height: 475 },
      },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 305, height: 406, bleed: 3 },
      { id: "back", label: "Rückseite", width: 305, height: 406, bleed: 3 },
      { id: "chest_left", label: "Brust links", width: 100, height: 100, bleed: 2 },
    ],
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1200&q=80&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    bestseller: true,
  },
  {
    id: "p_polo_classic",
    slug: "klassisches-polo-shirt",
    title: "Klassisches Polo-Shirt",
    category: "textilien",
    subcategory: "polo-shirts",
    type: "polo",
    priceFrom: 22.5,
    basePrice: 22.5,
    rating: 4.7,
    reviews: 812,
    description:
      "Elegantes Polo-Shirt für Business und Event. Hochwertige Pique-Qualität, 200 g/m².",
    highlights: [
      "Pique 200 g/m²",
      "Knopfleiste mit 3 Knöpfen",
      "Stickerei oder Druck möglich",
      "Premium Marken-Qualität",
    ],
    colors: tshirtColors,
    sizes: sizesApparel,
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 35, topPct: 26, widthPct: 30, heightPct: 44 },
        widthMm: 280,
        heightMm: 380,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "chest_left",
        key: "chest_left" as const,
        label: "Brust links",
        labelEn: "Left chest",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 54, topPct: 28, widthPct: 12, heightPct: 12 },
        widthMm: 80,
        heightMm: 80,
        recommendedDpi: 300,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 2.6,
      },
      {
        id: "sleeve_left",
        key: "sleeve_left" as const,
        label: "Ärmel links",
        labelEn: "Left sleeve",
        mockup: "/mockups/tshirt/side.png",
        mockupWidth: 1311,
        mockupHeight: 1200,
        printArea: { leftPct: 18, topPct: 22, widthPct: 22, heightPct: 22 },
        widthMm: 80,
        heightMm: 50,
        recommendedDpi: 300,
        safePct: 6,
        bleedPct: 0,
        additionalPrice: 2.9,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 319, y: 217, width: 274, height: 367 },
      },
    ],
    zones: [{ id: "front", label: "Brust", width: 80, height: 80, bleed: 2 }],
    image:
      "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=1200&q=80&auto=format&fit=crop",
    ],
    bestseller: true,
  },
  {
    id: "p_hoodie",
    slug: "premium-hoodie",
    title: "Premium Hoodie mit Kapuze",
    category: "textilien",
    subcategory: "hoodies",
    type: "hoodie",
    priceFrom: 34.9,
    basePrice: 34.9,
    rating: 4.9,
    reviews: 1432,
    description:
      "Schwerer Premium-Hoodie, 320 g/m². Innen angeraut. Perfekt für Markenmerchandise.",
    highlights: ["320 g/m² Baumwoll-Mix", "Doppelter Kapuzensaum", "Kängurutasche", "Unisex Fit"],
    colors: tshirtColors,
    sizes: sizesApparel,
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 32, topPct: 28, widthPct: 36, heightPct: 42 },
        widthMm: 305,
        heightMm: 380,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "back",
        key: "back" as const,
        label: "Rückseite",
        labelEn: "Back",
        mockup: "/mockups/tshirt/back.png",
        mockupWidth: 840,
        mockupHeight: 848,
        printArea: { leftPct: 30, topPct: 22, widthPct: 40, heightPct: 52 },
        widthMm: 305,
        heightMm: 380,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 292, y: 234, width: 328, height: 350 },
      },
      {
        id: "back",
        label: "Rückseite",
        image: "/mockups/tshirt/back.png",
        area: { x: 252, y: 186, width: 336, height: 441 },
      },
    ],
    zones: [{ id: "front", label: "Vorderseite", width: 305, height: 380, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=1200&q=80&auto=format&fit=crop",
    ],
    badge: "Neu",
  },
  {
    id: "p_cap",
    slug: "snapback-cap",
    title: "Snapback Cap — bestickbar",
    category: "textilien",
    subcategory: "caps",
    type: "cap",
    priceFrom: 12.9,
    basePrice: 12.9,
    rating: 4.6,
    reviews: 412,
    description: "Klassische Snapback Cap mit ebenem Schirm. Ideal für Stickerei oder Patch-Druck.",
    highlights: ["6-Panel Design", "Verstellbarer Snap-Verschluss", "Einheitsgröße", "Stickerei möglich"],
    colors: [
      { name: "Schwarz", hex: "#111111" },
      { name: "Marine", hex: "#1E3A5F" },
      { name: "Weiß", hex: "#FFFFFF" },
    ],
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Front-Panel",
        labelEn: "Front panel",
        mockup: "/mockups/cap/cap.png",
        mockupWidth: 490,
        mockupHeight: 405,
        printArea: { leftPct: 35, topPct: 25, widthPct: 30, heightPct: 22 },
        widthMm: 120,
        heightMm: 60,
        recommendedDpi: 300,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/cap/cap.png",
        area: { x: 172, y: 101, width: 147, height: 89 },
      },
    ],
    zones: [{ id: "front", label: "Front", width: 120, height: 60, bleed: 2 }],
    image: "/mockups/cap/cap.png",
    gallery: ["/mockups/cap/cap.png"],
  },
  {
    id: "p_damen_tshirt",
    slug: "damen-t-shirt",
    title: "Damen T-Shirt — Bio Baumwolle",
    category: "textilien",
    subcategory: "damen-t-shirts",
    type: "tshirt",
    priceFrom: 15.9,
    basePrice: 15.9,
    rating: 4.8,
    reviews: 934,
    description:
      "Tailliertes Damen T-Shirt aus 100% Bio-Baumwolle, 160 g/m². Schmeichelhafter Schnitt für alle Größen.",
    highlights: [
      "100% Bio-Baumwolle, 160 g/m²",
      "Taillierter Damenschnitt",
      "OEKO-TEX® zertifiziert",
      "Vor-/Rückendruck möglich",
    ],
    colors: tshirtColors,
    sizes: sizesApparel,
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 33, topPct: 24, widthPct: 34, heightPct: 50 },
        widthMm: 280,
        heightMm: 380,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "back",
        key: "back" as const,
        label: "Rückseite",
        labelEn: "Back",
        mockup: "/mockups/tshirt/back.png",
        mockupWidth: 840,
        mockupHeight: 848,
        printArea: { leftPct: 32, topPct: 18, widthPct: 36, heightPct: 56 },
        widthMm: 280,
        heightMm: 380,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "chest_left",
        key: "chest_left" as const,
        label: "Brust links",
        labelEn: "Left chest",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 54, topPct: 26, widthPct: 13, heightPct: 14 },
        widthMm: 100,
        heightMm: 100,
        recommendedDpi: 300,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 2.6,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 301, y: 200, width: 310, height: 417 },
      },
      {
        id: "back",
        label: "Rückseite",
        image: "/mockups/tshirt/back.png",
        area: { x: 269, y: 153, width: 302, height: 475 },
      },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 280, height: 380, bleed: 3 },
      { id: "back", label: "Rückseite", width: 280, height: 380, bleed: 3 },
    ],
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=1200&q=80&auto=format&fit=crop",
    ],
    badge: "Bestseller",
    bestseller: true,
  },
  {
    id: "p_damen_polo",
    slug: "damen-polo-shirt",
    title: "Damen Polo-Shirt",
    category: "textilien",
    subcategory: "damen-polo-shirts",
    type: "polo",
    priceFrom: 24.9,
    basePrice: 24.9,
    rating: 4.7,
    reviews: 421,
    description:
      "Elegantes Damen Polo-Shirt aus hochwertiger Pique-Qualität, 200 g/m². Ideal für Business und Events.",
    highlights: [
      "Pique 200 g/m²",
      "Taillierter Damenschnitt",
      "Knopfleiste mit 3 Knöpfen",
      "Stickerei oder Druck möglich",
    ],
    colors: tshirtColors,
    sizes: sizesApparel,
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 35, topPct: 26, widthPct: 30, heightPct: 44 },
        widthMm: 260,
        heightMm: 360,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
      {
        id: "chest_left",
        key: "chest_left" as const,
        label: "Brust links",
        labelEn: "Left chest",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 54, topPct: 28, widthPct: 12, heightPct: 12 },
        widthMm: 80,
        heightMm: 80,
        recommendedDpi: 300,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 2.6,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 319, y: 217, width: 274, height: 367 },
      },
    ],
    zones: [
      { id: "front", label: "Brust", width: 80, height: 80, bleed: 2 },
    ],
    image:
      "https://images.unsplash.com/photo-1594938298603-c8148c4b1dea?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4b1dea?w=1200&q=80&auto=format&fit=crop",
    ],
    bestseller: true,
  },
  {
    id: "p_schuerze",
    slug: "kochschuerze",
    title: "Schürze — bedruckbar",
    category: "textilien",
    subcategory: "schuerzen",
    type: "tshirt",
    priceFrom: 18.9,
    basePrice: 18.9,
    rating: 4.6,
    reviews: 287,
    description:
      "Robuste Schürze aus 65% Polyester / 35% Baumwolle, 210 g/m². Einheitsgröße mit verstellbarem Nackenband.",
    highlights: [
      "65% Polyester / 35% Baumwolle, 210 g/m²",
      "Einheitsgröße, verstellbares Nackenband",
      "Großflächiger Druckbereich",
      "Ideal für Gastronomie & Events",
    ],
    colors: [
      { name: "Weiß", hex: "#FFFFFF" },
      { name: "Schwarz", hex: "#111111" },
      { name: "Marine", hex: "#1E3A5F" },
      { name: "Rot", hex: "#C03434" },
    ],
    placements: [
      {
        id: "front",
        key: "front" as const,
        label: "Vorderseite",
        labelEn: "Front",
        mockup: "/mockups/tshirt/front.png",
        mockupWidth: 912,
        mockupHeight: 834,
        printArea: { leftPct: 30, topPct: 30, widthPct: 40, heightPct: 48 },
        widthMm: 300,
        heightMm: 350,
        recommendedDpi: 150,
        safePct: 5,
        bleedPct: 0,
        additionalPrice: 0,
      },
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/tshirt/front.png",
        area: { x: 274, y: 251, width: 365, height: 401 },
      },
    ],
    zones: [{ id: "front", label: "Vorderseite", width: 300, height: 350, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=1200&q=80&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581888227599-779811939961?w=1200&q=80&auto=format&fit=crop",
    ],
    badge: "Neu",
  },
  {
    id: "p_flyer_a5",
    slug: "flyer-a5",
    title: "Flyer A5 — Premium",
    category: "flyer",
    subcategory: "flyer-a5",
    type: "flyer",
    priceFrom: 9.9,
    basePrice: 9.9,
    rating: 4.9,
    reviews: 3217,
    description: "Premium Flyer A5, 135 g/m² Bilderdruck. Brillante Farben, gestochen scharfer Druck.",
    highlights: [
      "Format: 148 × 210 mm",
      "135 g/m² Bilderdruck glänzend",
      "4/4-farbig (beidseitig)",
      "Ab 250 Stück",
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/flyer-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
      {
        id: "back",
        label: "Rückseite",
        image: "/mockups/flyer-back.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 148, height: 210, bleed: 3 },
      { id: "back", label: "Rückseite", width: 148, height: 210, bleed: 3 },
    ],
    image:
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=1200&q=80&auto=format&fit=crop",
    ],
    bestseller: true,
  },
  {
    id: "p_flyer_a6",
    slug: "flyer-a6",
    title: "Flyer A6",
    category: "flyer",
    subcategory: "flyer-a6",
    type: "flyer",
    priceFrom: 7.9,
    basePrice: 7.9,
    rating: 4.8,
    reviews: 0,
    description: "Kompakter Flyer im A6-Format. 135 g/m² Bilderdruck glänzend. Ideal für Ankündigungen, Gutscheine und Veranstaltungen.",
    highlights: [
      "Format: 105 × 148 mm",
      "135 g/m² Bilderdruck glänzend",
      "4/4-farbig (beidseitig)",
      "Ab 250 Stück",
    ],
    views: [
      { id: "front", label: "Vorderseite", image: "/mockups/flyer-front.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
      { id: "back", label: "Rückseite", image: "/mockups/flyer-back.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 105, height: 148, bleed: 3 },
      { id: "back", label: "Rückseite", width: 105, height: 148, bleed: 3 },
    ],
    image: "",
    gallery: [],
  },
  {
    id: "p_flyer_a4",
    slug: "flyer-a4",
    title: "Flyer A4",
    category: "flyer",
    subcategory: "flyer-a4",
    type: "flyer",
    priceFrom: 14.9,
    basePrice: 14.9,
    rating: 4.8,
    reviews: 0,
    description: "Großformatiger Flyer A4 für maximale Wirkung. 135 g/m² Bilderdruck glänzend. Perfekt für Werbung, Veranstaltungen und Informationsblätter.",
    highlights: [
      "Format: 210 × 297 mm",
      "135 g/m² Bilderdruck glänzend",
      "4/4-farbig (beidseitig)",
      "Ab 100 Stück",
    ],
    views: [
      { id: "front", label: "Vorderseite", image: "/mockups/flyer-front.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
      { id: "back", label: "Rückseite", image: "/mockups/flyer-back.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 210, height: 297, bleed: 3 },
      { id: "back", label: "Rückseite", width: 210, height: 297, bleed: 3 },
    ],
    image: "",
    gallery: [],
  },
  {
    id: "p_flyer_gefaltet",
    slug: "gefaltete-flyer",
    title: "Gefaltete Flyer",
    category: "flyer",
    subcategory: "gefaltete-flyer",
    type: "flyer",
    priceFrom: 19.9,
    basePrice: 19.9,
    rating: 4.7,
    reviews: 0,
    description: "Gefaltete Flyer mit Mittelfalz oder Wickelfalz. 150 g/m² Bilderdruck glänzend. Ideal für Speisekarten, Programme und Broschürchen.",
    highlights: [
      "Format gefaltet: A5 (148 × 210 mm)",
      "150 g/m² Bilderdruck glänzend",
      "Mittelfalz oder Wickelfalz",
      "Ab 100 Stück",
    ],
    views: [
      { id: "front", label: "Außenseite", image: "/mockups/flyer-front.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
      { id: "back", label: "Innenseite", image: "/mockups/flyer-back.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
    ],
    zones: [
      { id: "front", label: "Außenseite", width: 210, height: 210, bleed: 3 },
      { id: "back", label: "Innenseite", width: 210, height: 210, bleed: 3 },
    ],
    image: "",
    gallery: [],
  },
  {
    id: "p_flyer_express",
    slug: "express-flyer",
    title: "Express-Flyer",
    category: "flyer",
    subcategory: "express-flyer",
    type: "flyer",
    priceFrom: 14.9,
    basePrice: 14.9,
    rating: 4.9,
    reviews: 0,
    badge: "Express",
    description: "Flyer mit Expresslieferung — bereits am nächsten Werktag druckfertig. 135 g/m² Bilderdruck, Format A5.",
    highlights: [
      "Format: 148 × 210 mm",
      "135 g/m² Bilderdruck glänzend",
      "Lieferung in 24 h möglich",
      "Ab 100 Stück",
    ],
    views: [
      { id: "front", label: "Vorderseite", image: "/mockups/flyer-front.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
      { id: "back", label: "Rückseite", image: "/mockups/flyer-back.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 148, height: 210, bleed: 3 },
      { id: "back", label: "Rückseite", width: 148, height: 210, bleed: 3 },
    ],
    image: "",
    gallery: [],
  },
  {
    id: "p_flyer_beidseitig",
    slug: "beidseitig-flyer",
    title: "Beidseitig bedruckte Flyer",
    category: "flyer",
    subcategory: "beidseitig-flyer",
    type: "flyer",
    priceFrom: 9.9,
    basePrice: 9.9,
    rating: 4.8,
    reviews: 0,
    description: "Flyer beidseitig bedruckt in Premium-Qualität. 135 g/m² Bilderdruck. Vorder- und Rückseite individuell gestalten.",
    highlights: [
      "Format: 148 × 210 mm (A5)",
      "135 g/m² Bilderdruck glänzend",
      "Beidseitiger Vollfarbdruck",
      "Ab 250 Stück",
    ],
    views: [
      { id: "front", label: "Vorderseite", image: "/mockups/flyer-front.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
      { id: "back", label: "Rückseite", image: "/mockups/flyer-back.svg", area: { x: 200, y: 100, width: 600, height: 850 } },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 148, height: 210, bleed: 3 },
      { id: "back", label: "Rückseite", width: 148, height: 210, bleed: 3 },
    ],
    image: "",
    gallery: [],
  },
  {
    id: "p_visitenkarte_standard",
    slug: "visitenkarte-standard",
    title: "Visitenkarte Standard 85 × 55 mm",
    category: "visitenkarten",
    subcategory: "standard",
    type: "businesscard",
    priceFrom: 7.9,
    basePrice: 7.9,
    rating: 4.8,
    reviews: 4521,
    description: "Premium Visitenkarten in Standardformat. 350 g/m² Bilderdruck.",
    highlights: [
      "Format: 85 × 55 mm",
      "350 g/m² Premium Karton",
      "4/4-farbig",
      "Ab 100 Stück",
    ],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/bcard-front.svg",
        area: { x: 100, y: 200, width: 800, height: 520 },
      },
      {
        id: "back",
        label: "Rückseite",
        image: "/mockups/bcard-back.svg",
        area: { x: 100, y: 200, width: 800, height: 520 },
      },
    ],
    zones: [
      { id: "front", label: "Vorderseite", width: 85, height: 55, bleed: 2 },
      { id: "back", label: "Rückseite", width: 85, height: 55, bleed: 2 },
    ],
    image:
      "https://images.unsplash.com/photo-1606293459339-aa5dd9b48049?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1606293459339-aa5dd9b48049?w=1200&q=80&auto=format&fit=crop",
    ],
    bestseller: true,
  },
  {
    id: "p_poster_a3",
    slug: "poster-a3",
    title: "Plakat A3 — Hochglanz",
    category: "plakate",
    subcategory: "plakate-a3",
    type: "poster",
    priceFrom: 4.9,
    basePrice: 4.9,
    rating: 4.7,
    reviews: 921,
    description: "Hochglanz-Plakat A3, 170 g/m². Perfekt für Events und Werbung.",
    highlights: ["Format: 297 × 420 mm", "170 g/m² Bilderdruck", "Glänzend oder matt"],
    views: [
      {
        id: "front",
        label: "Vorderseite",
        image: "/mockups/poster-front.svg",
        area: { x: 100, y: 100, width: 800, height: 1100 },
      },
    ],
    zones: [{ id: "front", label: "Plakat", width: 297, height: 420, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1561070791-2526d30994b8?w=1200&q=80&auto=format&fit=crop",
    ],
  },
  {
    id: "p_broschuere_a5",
    slug: "broschuere-a5",
    title: "Broschüre A5 mit Heftung",
    category: "broschueren",
    subcategory: "broschueren-heftung",
    type: "brochure",
    priceFrom: 29.9,
    basePrice: 29.9,
    rating: 4.8,
    reviews: 312,
    description: "Hochwertige Broschüre A5 mit Drahtheftung. 16 Seiten, 135 g/m².",
    highlights: ["Format: 148 × 210 mm", "16 Seiten Standard", "Drahtheftung", "135 g/m² Bilderdruck"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 148, height: 210, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=1200&q=80&auto=format&fit=crop",
    ],
  },
  {
    id: "p_broschuere_a6",
    slug: "broschuere-a6",
    title: "Broschüre A6",
    category: "broschueren",
    subcategory: "broschueren-a6",
    type: "brochure",
    priceFrom: 19.9,
    basePrice: 19.9,
    rating: 4.7,
    reviews: 184,
    description: "Kompakte Broschüre im A6-Format. Ideal für Produktkataloge und Menükarten.",
    highlights: ["Format: 105 × 148 mm", "16 Seiten Standard", "135 g/m² Bilderdruck", "Drahtheftung"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 105, height: 148, bleed: 3 }],
    image: "",
    gallery: [],
  },
  {
    id: "p_broschuere_a5_std",
    slug: "broschuere-a5-standard",
    title: "Broschüre A5",
    category: "broschueren",
    subcategory: "broschueren-a5",
    type: "brochure",
    priceFrom: 24.9,
    basePrice: 24.9,
    rating: 4.8,
    reviews: 263,
    description: "Klassische Broschüre A5 — perfekt für Firmenprofile und Angebotshefte.",
    highlights: ["Format: 148 × 210 mm", "16 Seiten Standard", "135 g/m² Bilderdruck", "Drahtheftung"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 148, height: 210, bleed: 3 }],
    image: "",
    gallery: [],
  },
  {
    id: "p_broschuere_a4",
    slug: "broschuere-a4",
    title: "Broschüre A4",
    category: "broschueren",
    subcategory: "broschueren-a4",
    type: "brochure",
    priceFrom: 34.9,
    basePrice: 34.9,
    rating: 4.8,
    reviews: 197,
    description: "Großformatige Broschüre A4 — ideal für Jahresberichte und Kataloge.",
    highlights: ["Format: 210 × 297 mm", "16 Seiten Standard", "135 g/m² Bilderdruck", "Drahtheftung oder Klebebindung"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 210, height: 297, bleed: 3 }],
    image: "",
    gallery: [],
  },
  {
    id: "p_broschuere_a3",
    slug: "broschuere-a3",
    title: "Broschüre A3",
    category: "broschueren",
    subcategory: "broschueren-a3",
    type: "brochure",
    priceFrom: 44.9,
    basePrice: 44.9,
    rating: 4.6,
    reviews: 89,
    description: "Großformat-Broschüre A3 — prägnante Präsentationen und Ausstellungshefte.",
    highlights: ["Format: 297 × 420 mm", "16 Seiten Standard", "135 g/m² Bilderdruck", "Drahtheftung"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 297, height: 420, bleed: 3 }],
    image: "",
    gallery: [],
  },
  {
    id: "p_broschuere_gefaltet",
    slug: "broschuere-gefaltet",
    title: "Gefaltete Broschüre",
    category: "broschueren",
    subcategory: "gefaltete-broschueren",
    type: "brochure",
    priceFrom: 22.9,
    basePrice: 22.9,
    rating: 4.7,
    reviews: 143,
    description: "Gefaltete Broschüre als Wickel-, Zickzack- oder Leporello-Falz — ohne Heftung.",
    highlights: ["Mehrere Falzarten", "Format wählbar", "135 g/m² Bilderdruck", "Beidseitiger Druck"],
    views: [
      {
        id: "cover",
        label: "Cover",
        image: "/mockups/brochure-front.svg",
        area: { x: 200, y: 100, width: 600, height: 850 },
      },
    ],
    zones: [{ id: "cover", label: "Cover", width: 210, height: 297, bleed: 3 }],
    image: "",
    gallery: [],
  },
  {
    id: "p_stofftasche",
    slug: "stofftasche",
    title: "Stofftasche Bio-Baumwolle",
    category: "werbematerial",
    subcategory: "stofftaschen",
    type: "promo",
    priceFrom: 5.9,
    basePrice: 5.9,
    rating: 4.6,
    reviews: 654,
    description: "Nachhaltige Bio-Stofftasche mit Logo-Druck. Ideal als Werbegeschenk.",
    highlights: ["100% Bio-Baumwolle", "Lange Henkel", "1- oder 4-farbig bedruckbar"],
    colors: [
      { name: "Natur", hex: "#E8DDC7" },
      { name: "Schwarz", hex: "#111111" },
    ],
    views: [
      {
        id: "front",
        label: "Vorne",
        image:
          "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=1000&q=80&auto=format&fit=crop",
        area: { x: 300, y: 280, width: 400, height: 400 },
      },
    ],
    zones: [{ id: "front", label: "Vorne", width: 220, height: 220, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?w=1200&q=80&auto=format&fit=crop",
    ],
  },
  {
    id: "p_mousepad",
    slug: "mousepad",
    title: "Mousepad mit Vollflächendruck",
    category: "werbematerial",
    subcategory: "mousepads",
    type: "promo",
    priceFrom: 6.9,
    basePrice: 6.9,
    rating: 4.5,
    reviews: 221,
    description: "Mousepad mit individueller Bedruckung. Rutschfeste Unterseite.",
    highlights: ["220 × 180 mm", "Vollflächendruck", "Rutschfest"],
    views: [
      {
        id: "front",
        label: "Oberseite",
        image: "/mockups/mousepad.svg",
        area: { x: 100, y: 200, width: 800, height: 600 },
      },
    ],
    zones: [{ id: "front", label: "Oberseite", width: 220, height: 180, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=1200&q=80&auto=format&fit=crop",
    ],
  },
  {
    id: "p_regenschirm",
    slug: "regenschirm",
    title: "Regenschirm mit Logo-Druck",
    category: "werbematerial",
    subcategory: "regenschirme",
    type: "promo",
    priceFrom: 14.9,
    basePrice: 14.9,
    rating: 4.7,
    reviews: 154,
    description: "Premium Stockschirm mit Holzgriff und individuellem Logo-Druck.",
    highlights: ["8 Panels", "Holzgriff", "Windfest", "Logo-Druck inklusive"],
    views: [
      {
        id: "front",
        label: "Panel",
        image: "/mockups/umbrella.svg",
        area: { x: 200, y: 200, width: 600, height: 600 },
      },
    ],
    zones: [{ id: "front", label: "Panel", width: 200, height: 200, bleed: 3 }],
    image:
      "https://images.unsplash.com/photo-1534270804882-6b5048b1c1fc?w=800&q=80&auto=format&fit=crop",
    gallery: [
      "https://images.unsplash.com/photo-1534270804882-6b5048b1c1fc?w=1200&q=80&auto=format&fit=crop",
    ],
  },
];

export const PRODUCT_MAP = Object.fromEntries(PRODUCTS.map((p) => [p.slug, p]));

export function getProductsByCategory(slug: string) {
  return PRODUCTS.filter((p) => p.category === slug);
}

export function getBestsellers() {
  return PRODUCTS.filter((p) => p.bestseller);
}
